### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke virtual method 'android.net.Uri android.content.Intent.getData()' on a null object reference

### ISSUE THREAD

**Issue by kyounglee** [lukasgit/flutter_contacts#170]
Whenever I call **await ContactsService.openDeviceContactPicker()** and returned (using bottom right button) without any selection in contact list, the following exception occurs ( App dies. )

--EXCEPTION------------------------------------------
E/AndroidRuntime( 7385): java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=52943, result=1100, data=null} to activity { / }: java.lang.NullPointerException: Attempt to invoke virtual method 'android.net.Uri android.content.Intent.getData()' on a null object reference
E/AndroidRuntime( 7385): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:5360)
E/AndroidRuntime( 7385): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:5401)
E/AndroidRuntime( 7385): 	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
E/AndroidRuntime( 7385): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/AndroidRuntime( 7385): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/AndroidRuntime( 7385): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2267)
E/AndroidRuntime( 7385): 	at android.os.Handler.dispatchMessage(Handler.java:107)
E/AndroidRuntime( 7385): 	at android.os.Looper.loop(Looper.java:237)
E/AndroidRuntime( 7385): 	at android.app.ActivityThread.main(ActivityThread.java:8167)
E/AndroidRuntime( 7385): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 7385): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
E/AndroidRuntime( 7385): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
E/AndroidRuntime( 7385): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.net.Uri android.content.Intent.getData()' on a null object reference
E/AndroidRuntime( 7385): 	at flutter.plugins.contactsservice.contactsservice.ContactsServicePlugin$BaseContactsServiceDelegate.onActivityResult(ContactsServicePlugin.java:268)
E/AndroidRuntime( 7385): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry$FlutterEngineActivityPluginBinding.onActivityResult(FlutterEngineConnectionRegistry.java:739)
E/AndroidRuntime( 7385): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.onActivityResult(FlutterEngineConnectionRegistry.java:426)
E/AndroidRuntime( 7385): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onActivityResult(FlutterActivityAndFragmentDelegate.java:652)
E/AndroidRuntime( 7385): 	at io.flutter.embedding.android.FlutterActivity.onActivityResult(FlutterActivity.java:618)
E/AndroidRuntime( 7385): 	at net.e4net.CherryTalk.MainActivity.onActivityResult(MainActivity.java:133)
E/AndroidRuntime( 7385): 	at android.app.Activity.dispatchActivityResult(Activity.java:8300)
E/AndroidRuntime( 7385): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:5353)
E/AndroidRuntime( 7385): 	... 11 more
I/Process ( 7385): Sending signal. PID: 7385 SIG: 9
Lost connection to device.

public class MainActivity extends FlutterActivity {
     ::
    @Override
    protected void onActivityResult(int requestCode, int resultCode, @Nullable Intent data) {
        super.onActivityResult(requestCode, resultCode, data);  **<-- dies if data == null** 
    }
}
--ENVIRONMENT---------------------------------------

contacts_service 0.4.6 / Android 10

flutter doctor -v
[√] Flutter (Channel dev, 1.24.0-10.2.pre, on Microsoft Windows [Version 10.0.19041.630], locale ko-KR)
    • Flutter version 1.24.0-10.2.pre at C:\flutter
    • Framework revision 022b333a08 (12 days ago), 2020-11-18 11:35:09 -0800
    • Engine revision 07c1eed46b
    • Dart version 2.12.0 (build 2.12.0-29.10.beta)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\dklee\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (3 available)
    • SM N960N (mobile) • 2958a1d5be1c7ece • android-arm64  • Android 10 (API 29)
    • Web Server (web)  • web-server       • web-javascript • Flutter Tools
    • Chrome (web)      • chrome           • web-javascript • Google Chrome 86.0.4240.183

• No issues found!

**Comment by madhukesh048** [comment]
Any update on this issue?

**Comment by EugeneLes** [comment]
I am faced the same issue on Samsung S10 device

E/AndroidRuntime: FATAL EXCEPTION: main
    java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=52943, result=1100, data=null} to activity {/...MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'android.net.Uri android.content.Intent.getData()' on a null object reference
        at android.app.ActivityThread.deliverResults(ActivityThread.java:5506)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:5547)
        at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2307)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:246)
        at android.app.ActivityThread.main(ActivityThread.java:8506)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.net.Uri android.content.Intent.getData()' on a null object reference
        at flutter.plugins.contactsservice.contactsservice.ContactsServicePlugin$BaseContactsServiceDelegate.onActivityResult(ContactsServicePlugin.java:268)
        at io.flutter.embedding.engine.FlutterEnginePluginRegistry$FlutterEngineActivityPluginBinding.onActivityResult(FlutterEnginePluginRegistry.java:691)
        at io.flutter.embedding.engine.FlutterEnginePluginRegistry.onActivityResult(FlutterEnginePluginRegistry.java:378)
        at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onActivityResult(FlutterActivityAndFragmentDelegate.java:625)
        at io.flutter.embedding.android.FlutterActivity.onActivityResult(FlutterActivity.java:583)
        at android.app.Activity.dispatchActivityResult(Activity.java:8541)
        at android.app.ActivityThread.deliverResults(ActivityThread.java:5499)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:5547) 
        at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2307) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:246) 
        at android.app.ActivityThread.main(ActivityThread.java:8506) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)

**Comment by TheHazeEffect** [comment]
I also have this issue, seems like Missing null check before getData is called

**Comment by TheHazeEffect** [comment]
I was just testing the plugin with flutter 2.0.6

I wonder if this Merged Issue fixes it on the flutter side 
https://github.com/flutter/engine/pull/21806

**Comment by lukasgit** [comment]
Please feel free to submit a workable PR to staging branch. Thanks

**Comment by TheHazeEffect** [comment]
Well, it only seems to affect old versions of the plugin, not the current one.

So this'll only be an issue for Apps that haven't migrated to flutter 2 I believe and are still using 0.4.6

**Comment by lqmminh** [comment]
Any update on this issue?

**Comment by AnAlpaca** [comment]
Guys i really am new to flutter as a whole but from what ive managed to see is that problem lies in the code below:
I think a null check on intent should solve the issue. I am trying to do this on my end, but I dont have too much experience with java, as well as editting plugins. I added the null check and just got a bunch of errors, maybe someone with more experience could attempt this.
```
public boolean onActivityResult(int requestCode, int resultCode, Intent intent) {
      if(requestCode == REQUEST_OPEN_EXISTING_CONTACT || requestCode == REQUEST_OPEN_CONTACT_FORM) {
        try {
          Uri ur = intent.getData();
          finishWithResult(getContactByIdentifier(ur.getLastPathSegment()));
        } catch (NullPointerException e) {
          finishWithResult(FORM_OPERATION_CANCELED);
        }
        return true;
      }

      if (requestCode == REQUEST_OPEN_CONTACT_PICKER) {
        if (resultCode == RESULT_CANCELED) {
          finishWithResult(FORM_OPERATION_CANCELED);
          return true;
        }
        
        Uri contactUri = intent.getData();
        Cursor cursor = contentResolver.query(contactUri, null, null, null, null);
        if (cursor.moveToFirst()) {
          String id = contactUri.getLastPathSegment();
          getContacts("openDeviceContactPicker", id, false, false, false, localizedLabels, this.result);
        } else {
          Log.e(LOG_TAG, "onActivityResult - cursor.moveToFirst() returns false");
          finishWithResult(FORM_OPERATION_CANCELED);
        }
        cursor.close();
        return true;
      }

      finishWithResult(FORM_COULD_NOT_BE_OPEN);
      return false;
    }
```

**Comment by AnAlpaca** [comment]
I have managed to solve the issue by adding the null get as simply as follows:

```
public boolean onActivityResult(int requestCode, int resultCode, Intent intent) {
      if(requestCode == REQUEST_OPEN_EXISTING_CONTACT || requestCode == REQUEST_OPEN_CONTACT_FORM) {
        try {
          Uri ur = intent.getData();
          finishWithResult(getContactByIdentifier(ur.getLastPathSegment()));
        } catch (NullPointerException e) {
          finishWithResult(FORM_OPERATION_CANCELED);
        }
        return true;
      }

      if (requestCode == REQUEST_OPEN_CONTACT_PICKER) {
        if (resultCode == RESULT_CANCELED) {
          finishWithResult(FORM_OPERATION_CANCELED);
          return true;
        }
        Cursor cursor = null;
        if (intent != null){
        Uri contactUri = intent.getData();
        cursor = contentResolver.query(contactUri, null, null, null, null);
        if (cursor.moveToFirst()) {
          String id = contactUri.getLastPathSegment();
          getContacts("openDeviceContactPicker", id, false, false, false, localizedLabels, this.result);
        } else {
          Log.e(LOG_TAG, "onActivityResult - cursor.moveToFirst() returns false");
          finishWithResult(FORM_OPERATION_CANCELED);
        }}else{return true;}
        cursor.close();
        return true;
      }

      finishWithResult(FORM_COULD_NOT_BE_OPEN);
      return false;
    }
```
Now going back takes me straight back to the app without the fatal error. I probably isnt the best way to fix it but it worked for me.

**Comment by heshaShawky** [comment]
> Upgrade to Flutter 2
> 
> [#170 (comment)](https://github.com/lukasgit/flutter_contacts/issues/170#issuecomment-839483180)

The issue is still active on the recent flutter version that is 2.10.2

Plugin version: 
```pubspec
dependencies:
  contacts_service: ^0.6.3
  image_picker: ^0.8.4+10
```

```bash
eshams-MacBook-Pro:masarifi_app esham$ flutter doctor -v
[✓] Flutter (Channel stable, 2.10.2, on macOS 11.4 20F71 darwin-x64, locale en-EG)
    • Flutter version 2.10.2 at /Users/esham/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 097d3313d8 (11 days ago), 2022-02-18 19:33:08 -0600
    • Engine revision a83ed0e5e3
    • Dart version 2.16.1
    • DevTools version 2.9.2

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/esham/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS (Xcode 13.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.64.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.34.0

[✓] VS Code (version 1.33.1)
    • VS Code at /Volumes/Partion-2/Sources/Visual Studio Code.app/Contents
    • Flutter extension version 3.34.0

[✓] Connected device (2 available)
    • Redmi Note 8 Pro (mobile) • hev4t4bqo7hyvsnf • android-arm64  • Android 10 (API 29)
    • Chrome (web)              • chrome           • web-javascript • Google Chrome 98.0.4758.109

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

Issue log:
```bash
D[/AndroidRuntime]()(29357): Shutting down VM
E[/AndroidRuntime]()(29357): FATAL EXCEPTION: main
E[/AndroidRuntime]()(29357): Process: app.masarifi, PID: 29357
E[/AndroidRuntime]()(29357): java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=2346, result=-1, data=Intent { flg=0x1 clip={image* U:[content://com.android.providers.media.documents/document/image%3A108496]() ...} }} to activity {app.masarifi[/app.masarifi.MainActivity]()}: java.lang.IllegalStateException: Reply already submitted
E[/AndroidRuntime]()(29357): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4965)
E[/AndroidRuntime]()(29357): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:5006)
E[/AndroidRuntime]()(29357): 	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
E[/AndroidRuntime]()(29357): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E[/AndroidRuntime]()(29357): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E[/AndroidRuntime]()(29357): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2068)
E[/AndroidRuntime]()(29357): 	at android.os.Handler.dispatchMessage(Handler.java:107)
E[/AndroidRuntime]()(29357): 	at android.os.Looper.loop(Looper.java:224)
E[/AndroidRuntime]()(29357): 	at android.app.ActivityThread.main(ActivityThread.java:7551)
E[/AndroidRuntime]()(29357): 	at java.lang.reflect.Method.invoke(Native Method)
E[/AndroidRuntime]()(29357): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
E[/AndroidRuntime]()(29357): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:995)
E[/AndroidRuntime]()(29357): Caused by: java.lang.IllegalStateException: Reply already submitted
E[/AndroidRuntime]()(29357): 	at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:431)
E[/AndroidRuntime]()(29357): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:267)
E[/AndroidRuntime]()(29357): 	at flutter.plugins.contactsservice.contactsservice.ContactsServicePlugin$BaseContactsServiceDelegate.finishWithResult(ContactsServicePlugin.java:267)
E[/AndroidRuntime]()(29357): 	at flutter.plugins.contactsservice.contactsservice.ContactsServicePlugin$BaseContactsServiceDelegate.onActivityResult(ContactsServicePlugin.java:302)
E[/AndroidRuntime]()(29357): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry$FlutterEngineActivityPluginBinding.onActivityResult(FlutterEngineConnectionRegistry.java:840)
E[/AndroidRuntime]()(29357): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.onActivityResult(FlutterEngineConnectionRegistry.java:441)
E[/AndroidRuntime]()(29357): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onActivityResult(FlutterActivityAndFragmentDelegate.java:772)
E[/AndroidRuntime]()(29357): 	at io.flutter.embedding.android.FlutterActivity.onActivityResult(FlutterActivity.java:685)
E[/AndroidRuntime]()(29357): 	at android.app.Activity.dispatchActivityResult(Activity.java:8249)
E[/AndroidRuntime]()(29357): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4958)
E[/AndroidRuntime]()(29357): 	... 11 more
I[/Process]() (29357): Sending signal. PID: 29357 SIG: 9
Lost connection to device.
```

**Comment by jeromeDms** [comment]
> > Upgrade to Flutter 2
> > [#170 (comment)](https://github.com/lukasgit/flutter_contacts/issues/170#issuecomment-839483180)
> 
> The issue is still active on the recent flutter version that is 2.10.2
> 
> Plugin version:
> 
> ```
> dependencies:
>   contacts_service: ^0.6.3
>   image_picker: ^0.8.4+10
> ```
> 
>  ```shell
> eshams-MacBook-Pro:masarifi_app esham$ flutter doctor -v
> [✓] Flutter (Channel stable, 2.10.2, on macOS 11.4 20F71 darwin-x64, locale en-EG)
>     • Flutter version 2.10.2 at /Users/esham/Development/flutter
>     • Upstream repository https://github.com/flutter/flutter.git
>     • Framework revision 097d3313d8 (11 days ago), 2022-02-18 19:33:08 -0600
>     • Engine revision a83ed0e5e3
>     • Dart version 2.16.1
>     • DevTools version 2.9.2
> 
> [!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
>     • Android SDK at /Users/esham/Library/Android/sdk
>     ✗ cmdline-tools component is missing
>       Run `path/to/sdkmanager --install "cmdline-tools;latest"`
>       See https://developer.android.com/studio/command-line for more details.
>     ✗ Android license status unknown.
>       Run `flutter doctor --android-licenses` to accept the SDK licenses.
>       See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
> 
> [✓] Xcode - develop for iOS and macOS (Xcode 13.0)
>     • Xcode at /Applications/Xcode.app/Contents/Developer
>     • CocoaPods version 1.10.1
> 
> [✓] Chrome - develop for the web
>     • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
> 
> [✓] Android Studio (version 2020.3)
>     • Android Studio at /Applications/Android Studio.app/Contents
>     • Flutter plugin can be installed from:
>       🔨 https://plugins.jetbrains.com/plugin/9212-flutter
>     • Dart plugin can be installed from:
>       🔨 https://plugins.jetbrains.com/plugin/6351-dart
>     • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
> 
> [✓] VS Code (version 1.64.2)
>     • VS Code at /Applications/Visual Studio Code.app/Contents
>     • Flutter extension version 3.34.0
> 
> [✓] VS Code (version 1.33.1)
>     • VS Code at /Volumes/Partion-2/Sources/Visual Studio Code.app/Contents
>     • Flutter extension version 3.34.0
> 
> [✓] Connected device (2 available)
>     • Redmi Note 8 Pro (mobile) • hev4t4bqo7hyvsnf • android-arm64  • Android 10 (API 29)
>     • Chrome (web)              • chrome           • web-javascript • Google Chrome 98.0.4758.109
> 
> [✓] HTTP Host Availability
>     • All required HTTP hosts are available
> 
> ! Doctor found issues in 1 category.
> ```
> 
> Issue log:
> 
> ```shell
> D[/AndroidRuntime]()(29357): Shutting down VM
> E[/AndroidRuntime]()(29357): FATAL EXCEPTION: main
> E[/AndroidRuntime]()(29357): Process: app.masarifi, PID: 29357
> E[/AndroidRuntime]()(29357): java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=2346, result=-1, data=Intent { flg=0x1 clip={image* U:[content://com.android.providers.media.documents/document/image%3A108496]() ...} }} to activity {app.masarifi[/app.masarifi.MainActivity]()}: java.lang.IllegalStateException: Reply already submitted
> E[/AndroidRuntime]()(29357): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4965)
> E[/AndroidRuntime]()(29357): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:5006)
> E[/AndroidRuntime]()(29357): 	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
> E[/AndroidRuntime]()(29357): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
> E[/AndroidRuntime]()(29357): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
> E[/AndroidRuntime]()(29357): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2068)
> E[/AndroidRuntime]()(29357): 	at android.os.Handler.dispatchMessage(Handler.java:107)
> E[/AndroidRuntime]()(29357): 	at android.os.Looper.loop(Looper.java:224)
> E[/AndroidRuntime]()(29357): 	at android.app.ActivityThread.main(ActivityThread.java:7551)
> E[/AndroidRuntime]()(29357): 	at java.lang.reflect.Method.invoke(Native Method)
> E[/AndroidRuntime]()(29357): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
> E[/AndroidRuntime]()(29357): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:995)
> E[/AndroidRuntime]()(29357): Caused by: java.lang.IllegalStateException: Reply already submitted
> E[/AndroidRuntime]()(29357): 	at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:431)
> E[/AndroidRuntime]()(29357): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:267)
> E[/AndroidRuntime]()(29357): 	at flutter.plugins.contactsservice.contactsservice.ContactsServicePlugin$BaseContactsServiceDelegate.finishWithResult(ContactsServicePlugin.java:267)
> E[/AndroidRuntime]()(29357): 	at flutter.plugins.contactsservice.contactsservice.ContactsServicePlugin$BaseContactsServiceDelegate.onActivityResult(ContactsServicePlugin.java:302)
> E[/AndroidRuntime]()(29357): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry$FlutterEngineActivityPluginBinding.onActivityResult(FlutterEngineConnectionRegistry.java:840)
> E[/AndroidRuntime]()(29357): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.onActivityResult(FlutterEngineConnectionRegistry.java:441)
> E[/AndroidRuntime]()(29357): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onActivityResult(FlutterActivityAndFragmentDelegate.java:772)
> E[/AndroidRuntime]()(29357): 	at io.flutter.embedding.android.FlutterActivity.onActivityResult(FlutterActivity.java:685)
> E[/AndroidRuntime]()(29357): 	at android.app.Activity.dispatchActivityResult(Activity.java:8249)
> E[/AndroidRuntime]()(29357): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4958)
> E[/AndroidRuntime]()(29357): 	... 11 more
> I[/Process]() (29357): Sending signal. PID: 29357 SIG: 9
> Lost connection to device.
> ```

Hi
Same problem here, did you find a way to solve this ?
Thanks
