### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by nayansolanki001** [lukasgit/flutter_contacts#218]
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.AssetFileDescriptor android.content.ContentResolver.openAssetFileDescriptor(android.net.Uri, java.lang.String)' on a null object reference
       at android.provider.ContactsContract$Contacts.openContactPhotoInputStream(ContactsContract.java:2164)
       at flutter.plugins.contactsservice.contactsservice.ContactsServicePlugin.b(ContactsServicePlugin.java:11)
       at flutter.plugins.contactsservice.contactsservice.ContactsServicePlugin.access$000(ContactsServicePlugin.java)
       at flutter.plugins.contactsservice.contactsservice.ContactsServicePlugin$GetContactsTask.doInBackground(ContactsServicePlugin.java:132)
       at flutter.plugins.contactsservice.contactsservice.ContactsServicePlugin$GetContactsTask.doInBackground(ContactsServicePlugin.java)
       at android.os.AsyncTask$3.call(AsyncTask.java:378)
       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:919)

**Comment by lukasgit** [comment]
@nayansolanki001 which version are you using?

> 0.6.0
> 0.6.1
>

**Comment by nayansolanki001** [comment]
0.6.0

**Comment by lukasgit** [comment]
@nayansolanki001 I believe this issue was fixed in version 0.6.1

**Comment by nayansolanki001** [comment]
now i am using v 0.6.1 therefor get this issue

**Comment by sonubabu7373** [comment]
I am using 0.6.3 the latest version.. Still getting the issue....Firebase crashlytics reporting this issue again and again in Samsung device
