### ISSUE TITLE
Error when when retreiving contacts

### ISSUE THREAD

**Issue by b-cancel** [lukasgit/flutter_contacts#6]
this is the error i get
It causes a weird flicker in my butter smooth UI
W/System (25860): A resource failed to call close.

**Comment by b-cancel** [comment]
@lukasgit please help! 
even pointing in the right direction would be great

Currently, I'm calling it as such

```
List<Contact> contacts.value = (await ContactsService.getContacts(
        withThumbnails: false,
      )).toList(); 
```

**Comment by lukasgit** [comment]
@b-cancel it might be related to PR #7 ... I just pushed a new build v0.3.0 so please upgrade your package and try again. Thanks!

**Comment by b-cancel** [comment]
@lukasgit this did not fix the problem
However, it's confirmed the flicker is not caused by the plugin
If i call get contacts twice back to back with the no thumbnails option no flicker occurs

when I instead call it with thumbnails all my contact widgets use the image instead of the icon
and thats when they flicker

it would be nice to get this fixed but all I could think of was to manually set the size of the container that holds either the icon or image... but the problem remained

Ill post a link here of the widget I am building so you can perhaps find a way to solve the problem

NOTE: the reason I ask for your help if you are willing is that it addresses a fairly common scenario
that you want to get contacts quickly and then load in the thumbnails after

Also the project I am using the plugin for is creating my own custom contact picker with all the add, edit, and remove contact functionality

so It might be a good way to show that everything is working for you guys as well

**Comment by lukasgit** [comment]
@b-cancel heads up, I am not the original author of this plugin.  This plugin was written early on and has its limitations.  The issue you are experiencing might be related to the limitations.  We are working on re-writing a new plugin to replace this plugin from the ground up that is clean, secure, flexible, and easy to maintain.

Our resources are limited, but please feel free to contribute to the current plugin with fixes / improvements you have. Please see the README for more information on how to contribute. Thanks!
